-- Auto-generated by gen_lut.py -- do not edit by hand
-- Source of truth: sim/python/gen_lut.py

library ieee;
use ieee.numeric_std.all;

package vis_warp_luts_pkg is

    -- ---- Aspect-corrected r2 weights, Q0.24 ----
    -- Chosen so corner r2_norm == 2^24 for the target core/AR.
    constant LUT_AX2_Q24 : integer := 508;
    constant LUT_AY2_Q24 : integer := 498;

    -- ---- Bloom mix factor, Q0.8 (M2.75) ----
    -- out = (orig*(256 - LUT_BLOOM_MIX_Q8) + blur*LUT_BLOOM_MIX_Q8) >> 8
    constant LUT_BLOOM_MIX_Q8 : integer := 64;

    -- ---- Warp M LUT: 257 entries, Q1.15 ----
    -- K_LUT = 0.3, K2_LUT = 0.0
    type warp_lut_t is array (0 to 256) of unsigned(15 downto 0);
    constant WARP_LUT : warp_lut_t := (
          0 => to_unsigned(32768, 16),  -- idx 0, r2=0.0000, M=1.0000
          1 => to_unsigned(32806, 16),  -- idx 1, r2=0.0039, M=1.0012
          2 => to_unsigned(32845, 16),  -- idx 2, r2=0.0078, M=1.0023
          3 => to_unsigned(32883, 16),  -- idx 3, r2=0.0117, M=1.0035
          4 => to_unsigned(32922, 16),  -- idx 4, r2=0.0156, M=1.0047
          5 => to_unsigned(32960, 16),  -- idx 5, r2=0.0195, M=1.0059
          6 => to_unsigned(32998, 16),  -- idx 6, r2=0.0234, M=1.0070
          7 => to_unsigned(33037, 16),  -- idx 7, r2=0.0273, M=1.0082
          8 => to_unsigned(33075, 16),  -- idx 8, r2=0.0312, M=1.0094
          9 => to_unsigned(33114, 16),  -- idx 9, r2=0.0352, M=1.0106
         10 => to_unsigned(33152, 16),  -- idx 10, r2=0.0391, M=1.0117
         11 => to_unsigned(33190, 16),  -- idx 11, r2=0.0430, M=1.0129
         12 => to_unsigned(33229, 16),  -- idx 12, r2=0.0469, M=1.0141
         13 => to_unsigned(33267, 16),  -- idx 13, r2=0.0508, M=1.0152
         14 => to_unsigned(33306, 16),  -- idx 14, r2=0.0547, M=1.0164
         15 => to_unsigned(33344, 16),  -- idx 15, r2=0.0586, M=1.0176
         16 => to_unsigned(33382, 16),  -- idx 16, r2=0.0625, M=1.0187
         17 => to_unsigned(33421, 16),  -- idx 17, r2=0.0664, M=1.0199
         18 => to_unsigned(33459, 16),  -- idx 18, r2=0.0703, M=1.0211
         19 => to_unsigned(33498, 16),  -- idx 19, r2=0.0742, M=1.0223
         20 => to_unsigned(33536, 16),  -- idx 20, r2=0.0781, M=1.0234
         21 => to_unsigned(33574, 16),  -- idx 21, r2=0.0820, M=1.0246
         22 => to_unsigned(33613, 16),  -- idx 22, r2=0.0859, M=1.0258
         23 => to_unsigned(33651, 16),  -- idx 23, r2=0.0898, M=1.0269
         24 => to_unsigned(33690, 16),  -- idx 24, r2=0.0938, M=1.0281
         25 => to_unsigned(33728, 16),  -- idx 25, r2=0.0977, M=1.0293
         26 => to_unsigned(33766, 16),  -- idx 26, r2=0.1016, M=1.0305
         27 => to_unsigned(33805, 16),  -- idx 27, r2=0.1055, M=1.0316
         28 => to_unsigned(33843, 16),  -- idx 28, r2=0.1094, M=1.0328
         29 => to_unsigned(33882, 16),  -- idx 29, r2=0.1133, M=1.0340
         30 => to_unsigned(33920, 16),  -- idx 30, r2=0.1172, M=1.0352
         31 => to_unsigned(33958, 16),  -- idx 31, r2=0.1211, M=1.0363
         32 => to_unsigned(33997, 16),  -- idx 32, r2=0.1250, M=1.0375
         33 => to_unsigned(34035, 16),  -- idx 33, r2=0.1289, M=1.0387
         34 => to_unsigned(34074, 16),  -- idx 34, r2=0.1328, M=1.0399
         35 => to_unsigned(34112, 16),  -- idx 35, r2=0.1367, M=1.0410
         36 => to_unsigned(34150, 16),  -- idx 36, r2=0.1406, M=1.0422
         37 => to_unsigned(34189, 16),  -- idx 37, r2=0.1445, M=1.0434
         38 => to_unsigned(34227, 16),  -- idx 38, r2=0.1484, M=1.0445
         39 => to_unsigned(34266, 16),  -- idx 39, r2=0.1523, M=1.0457
         40 => to_unsigned(34304, 16),  -- idx 40, r2=0.1562, M=1.0469
         41 => to_unsigned(34342, 16),  -- idx 41, r2=0.1602, M=1.0480
         42 => to_unsigned(34381, 16),  -- idx 42, r2=0.1641, M=1.0492
         43 => to_unsigned(34419, 16),  -- idx 43, r2=0.1680, M=1.0504
         44 => to_unsigned(34458, 16),  -- idx 44, r2=0.1719, M=1.0516
         45 => to_unsigned(34496, 16),  -- idx 45, r2=0.1758, M=1.0527
         46 => to_unsigned(34534, 16),  -- idx 46, r2=0.1797, M=1.0539
         47 => to_unsigned(34573, 16),  -- idx 47, r2=0.1836, M=1.0551
         48 => to_unsigned(34611, 16),  -- idx 48, r2=0.1875, M=1.0562
         49 => to_unsigned(34650, 16),  -- idx 49, r2=0.1914, M=1.0574
         50 => to_unsigned(34688, 16),  -- idx 50, r2=0.1953, M=1.0586
         51 => to_unsigned(34726, 16),  -- idx 51, r2=0.1992, M=1.0598
         52 => to_unsigned(34765, 16),  -- idx 52, r2=0.2031, M=1.0609
         53 => to_unsigned(34803, 16),  -- idx 53, r2=0.2070, M=1.0621
         54 => to_unsigned(34842, 16),  -- idx 54, r2=0.2109, M=1.0633
         55 => to_unsigned(34880, 16),  -- idx 55, r2=0.2148, M=1.0645
         56 => to_unsigned(34918, 16),  -- idx 56, r2=0.2188, M=1.0656
         57 => to_unsigned(34957, 16),  -- idx 57, r2=0.2227, M=1.0668
         58 => to_unsigned(34995, 16),  -- idx 58, r2=0.2266, M=1.0680
         59 => to_unsigned(35034, 16),  -- idx 59, r2=0.2305, M=1.0692
         60 => to_unsigned(35072, 16),  -- idx 60, r2=0.2344, M=1.0703
         61 => to_unsigned(35110, 16),  -- idx 61, r2=0.2383, M=1.0715
         62 => to_unsigned(35149, 16),  -- idx 62, r2=0.2422, M=1.0727
         63 => to_unsigned(35187, 16),  -- idx 63, r2=0.2461, M=1.0738
         64 => to_unsigned(35226, 16),  -- idx 64, r2=0.2500, M=1.0750
         65 => to_unsigned(35264, 16),  -- idx 65, r2=0.2539, M=1.0762
         66 => to_unsigned(35302, 16),  -- idx 66, r2=0.2578, M=1.0773
         67 => to_unsigned(35341, 16),  -- idx 67, r2=0.2617, M=1.0785
         68 => to_unsigned(35379, 16),  -- idx 68, r2=0.2656, M=1.0797
         69 => to_unsigned(35418, 16),  -- idx 69, r2=0.2695, M=1.0809
         70 => to_unsigned(35456, 16),  -- idx 70, r2=0.2734, M=1.0820
         71 => to_unsigned(35494, 16),  -- idx 71, r2=0.2773, M=1.0832
         72 => to_unsigned(35533, 16),  -- idx 72, r2=0.2812, M=1.0844
         73 => to_unsigned(35571, 16),  -- idx 73, r2=0.2852, M=1.0855
         74 => to_unsigned(35610, 16),  -- idx 74, r2=0.2891, M=1.0867
         75 => to_unsigned(35648, 16),  -- idx 75, r2=0.2930, M=1.0879
         76 => to_unsigned(35686, 16),  -- idx 76, r2=0.2969, M=1.0891
         77 => to_unsigned(35725, 16),  -- idx 77, r2=0.3008, M=1.0902
         78 => to_unsigned(35763, 16),  -- idx 78, r2=0.3047, M=1.0914
         79 => to_unsigned(35802, 16),  -- idx 79, r2=0.3086, M=1.0926
         80 => to_unsigned(35840, 16),  -- idx 80, r2=0.3125, M=1.0938
         81 => to_unsigned(35878, 16),  -- idx 81, r2=0.3164, M=1.0949
         82 => to_unsigned(35917, 16),  -- idx 82, r2=0.3203, M=1.0961
         83 => to_unsigned(35955, 16),  -- idx 83, r2=0.3242, M=1.0973
         84 => to_unsigned(35994, 16),  -- idx 84, r2=0.3281, M=1.0984
         85 => to_unsigned(36032, 16),  -- idx 85, r2=0.3320, M=1.0996
         86 => to_unsigned(36070, 16),  -- idx 86, r2=0.3359, M=1.1008
         87 => to_unsigned(36109, 16),  -- idx 87, r2=0.3398, M=1.1020
         88 => to_unsigned(36147, 16),  -- idx 88, r2=0.3438, M=1.1031
         89 => to_unsigned(36186, 16),  -- idx 89, r2=0.3477, M=1.1043
         90 => to_unsigned(36224, 16),  -- idx 90, r2=0.3516, M=1.1055
         91 => to_unsigned(36262, 16),  -- idx 91, r2=0.3555, M=1.1066
         92 => to_unsigned(36301, 16),  -- idx 92, r2=0.3594, M=1.1078
         93 => to_unsigned(36339, 16),  -- idx 93, r2=0.3633, M=1.1090
         94 => to_unsigned(36378, 16),  -- idx 94, r2=0.3672, M=1.1102
         95 => to_unsigned(36416, 16),  -- idx 95, r2=0.3711, M=1.1113
         96 => to_unsigned(36454, 16),  -- idx 96, r2=0.3750, M=1.1125
         97 => to_unsigned(36493, 16),  -- idx 97, r2=0.3789, M=1.1137
         98 => to_unsigned(36531, 16),  -- idx 98, r2=0.3828, M=1.1148
         99 => to_unsigned(36570, 16),  -- idx 99, r2=0.3867, M=1.1160
        100 => to_unsigned(36608, 16),  -- idx 100, r2=0.3906, M=1.1172
        101 => to_unsigned(36646, 16),  -- idx 101, r2=0.3945, M=1.1183
        102 => to_unsigned(36685, 16),  -- idx 102, r2=0.3984, M=1.1195
        103 => to_unsigned(36723, 16),  -- idx 103, r2=0.4023, M=1.1207
        104 => to_unsigned(36762, 16),  -- idx 104, r2=0.4062, M=1.1219
        105 => to_unsigned(36800, 16),  -- idx 105, r2=0.4102, M=1.1230
        106 => to_unsigned(36838, 16),  -- idx 106, r2=0.4141, M=1.1242
        107 => to_unsigned(36877, 16),  -- idx 107, r2=0.4180, M=1.1254
        108 => to_unsigned(36915, 16),  -- idx 108, r2=0.4219, M=1.1266
        109 => to_unsigned(36954, 16),  -- idx 109, r2=0.4258, M=1.1277
        110 => to_unsigned(36992, 16),  -- idx 110, r2=0.4297, M=1.1289
        111 => to_unsigned(37030, 16),  -- idx 111, r2=0.4336, M=1.1301
        112 => to_unsigned(37069, 16),  -- idx 112, r2=0.4375, M=1.1313
        113 => to_unsigned(37107, 16),  -- idx 113, r2=0.4414, M=1.1324
        114 => to_unsigned(37146, 16),  -- idx 114, r2=0.4453, M=1.1336
        115 => to_unsigned(37184, 16),  -- idx 115, r2=0.4492, M=1.1348
        116 => to_unsigned(37222, 16),  -- idx 116, r2=0.4531, M=1.1359
        117 => to_unsigned(37261, 16),  -- idx 117, r2=0.4570, M=1.1371
        118 => to_unsigned(37299, 16),  -- idx 118, r2=0.4609, M=1.1383
        119 => to_unsigned(37338, 16),  -- idx 119, r2=0.4648, M=1.1395
        120 => to_unsigned(37376, 16),  -- idx 120, r2=0.4688, M=1.1406
        121 => to_unsigned(37414, 16),  -- idx 121, r2=0.4727, M=1.1418
        122 => to_unsigned(37453, 16),  -- idx 122, r2=0.4766, M=1.1430
        123 => to_unsigned(37491, 16),  -- idx 123, r2=0.4805, M=1.1441
        124 => to_unsigned(37530, 16),  -- idx 124, r2=0.4844, M=1.1453
        125 => to_unsigned(37568, 16),  -- idx 125, r2=0.4883, M=1.1465
        126 => to_unsigned(37606, 16),  -- idx 126, r2=0.4922, M=1.1476
        127 => to_unsigned(37645, 16),  -- idx 127, r2=0.4961, M=1.1488
        128 => to_unsigned(37683, 16),  -- idx 128, r2=0.5000, M=1.1500
        129 => to_unsigned(37722, 16),  -- idx 129, r2=0.5039, M=1.1512
        130 => to_unsigned(37760, 16),  -- idx 130, r2=0.5078, M=1.1523
        131 => to_unsigned(37798, 16),  -- idx 131, r2=0.5117, M=1.1535
        132 => to_unsigned(37837, 16),  -- idx 132, r2=0.5156, M=1.1547
        133 => to_unsigned(37875, 16),  -- idx 133, r2=0.5195, M=1.1559
        134 => to_unsigned(37914, 16),  -- idx 134, r2=0.5234, M=1.1570
        135 => to_unsigned(37952, 16),  -- idx 135, r2=0.5273, M=1.1582
        136 => to_unsigned(37990, 16),  -- idx 136, r2=0.5312, M=1.1594
        137 => to_unsigned(38029, 16),  -- idx 137, r2=0.5352, M=1.1606
        138 => to_unsigned(38067, 16),  -- idx 138, r2=0.5391, M=1.1617
        139 => to_unsigned(38106, 16),  -- idx 139, r2=0.5430, M=1.1629
        140 => to_unsigned(38144, 16),  -- idx 140, r2=0.5469, M=1.1641
        141 => to_unsigned(38182, 16),  -- idx 141, r2=0.5508, M=1.1652
        142 => to_unsigned(38221, 16),  -- idx 142, r2=0.5547, M=1.1664
        143 => to_unsigned(38259, 16),  -- idx 143, r2=0.5586, M=1.1676
        144 => to_unsigned(38298, 16),  -- idx 144, r2=0.5625, M=1.1688
        145 => to_unsigned(38336, 16),  -- idx 145, r2=0.5664, M=1.1699
        146 => to_unsigned(38374, 16),  -- idx 146, r2=0.5703, M=1.1711
        147 => to_unsigned(38413, 16),  -- idx 147, r2=0.5742, M=1.1723
        148 => to_unsigned(38451, 16),  -- idx 148, r2=0.5781, M=1.1734
        149 => to_unsigned(38490, 16),  -- idx 149, r2=0.5820, M=1.1746
        150 => to_unsigned(38528, 16),  -- idx 150, r2=0.5859, M=1.1758
        151 => to_unsigned(38566, 16),  -- idx 151, r2=0.5898, M=1.1769
        152 => to_unsigned(38605, 16),  -- idx 152, r2=0.5938, M=1.1781
        153 => to_unsigned(38643, 16),  -- idx 153, r2=0.5977, M=1.1793
        154 => to_unsigned(38682, 16),  -- idx 154, r2=0.6016, M=1.1805
        155 => to_unsigned(38720, 16),  -- idx 155, r2=0.6055, M=1.1816
        156 => to_unsigned(38758, 16),  -- idx 156, r2=0.6094, M=1.1828
        157 => to_unsigned(38797, 16),  -- idx 157, r2=0.6133, M=1.1840
        158 => to_unsigned(38835, 16),  -- idx 158, r2=0.6172, M=1.1852
        159 => to_unsigned(38874, 16),  -- idx 159, r2=0.6211, M=1.1863
        160 => to_unsigned(38912, 16),  -- idx 160, r2=0.6250, M=1.1875
        161 => to_unsigned(38950, 16),  -- idx 161, r2=0.6289, M=1.1887
        162 => to_unsigned(38989, 16),  -- idx 162, r2=0.6328, M=1.1898
        163 => to_unsigned(39027, 16),  -- idx 163, r2=0.6367, M=1.1910
        164 => to_unsigned(39066, 16),  -- idx 164, r2=0.6406, M=1.1922
        165 => to_unsigned(39104, 16),  -- idx 165, r2=0.6445, M=1.1934
        166 => to_unsigned(39142, 16),  -- idx 166, r2=0.6484, M=1.1945
        167 => to_unsigned(39181, 16),  -- idx 167, r2=0.6523, M=1.1957
        168 => to_unsigned(39219, 16),  -- idx 168, r2=0.6562, M=1.1969
        169 => to_unsigned(39258, 16),  -- idx 169, r2=0.6602, M=1.1981
        170 => to_unsigned(39296, 16),  -- idx 170, r2=0.6641, M=1.1992
        171 => to_unsigned(39334, 16),  -- idx 171, r2=0.6680, M=1.2004
        172 => to_unsigned(39373, 16),  -- idx 172, r2=0.6719, M=1.2016
        173 => to_unsigned(39411, 16),  -- idx 173, r2=0.6758, M=1.2027
        174 => to_unsigned(39450, 16),  -- idx 174, r2=0.6797, M=1.2039
        175 => to_unsigned(39488, 16),  -- idx 175, r2=0.6836, M=1.2051
        176 => to_unsigned(39526, 16),  -- idx 176, r2=0.6875, M=1.2062
        177 => to_unsigned(39565, 16),  -- idx 177, r2=0.6914, M=1.2074
        178 => to_unsigned(39603, 16),  -- idx 178, r2=0.6953, M=1.2086
        179 => to_unsigned(39642, 16),  -- idx 179, r2=0.6992, M=1.2098
        180 => to_unsigned(39680, 16),  -- idx 180, r2=0.7031, M=1.2109
        181 => to_unsigned(39718, 16),  -- idx 181, r2=0.7070, M=1.2121
        182 => to_unsigned(39757, 16),  -- idx 182, r2=0.7109, M=1.2133
        183 => to_unsigned(39795, 16),  -- idx 183, r2=0.7148, M=1.2144
        184 => to_unsigned(39834, 16),  -- idx 184, r2=0.7188, M=1.2156
        185 => to_unsigned(39872, 16),  -- idx 185, r2=0.7227, M=1.2168
        186 => to_unsigned(39910, 16),  -- idx 186, r2=0.7266, M=1.2180
        187 => to_unsigned(39949, 16),  -- idx 187, r2=0.7305, M=1.2191
        188 => to_unsigned(39987, 16),  -- idx 188, r2=0.7344, M=1.2203
        189 => to_unsigned(40026, 16),  -- idx 189, r2=0.7383, M=1.2215
        190 => to_unsigned(40064, 16),  -- idx 190, r2=0.7422, M=1.2227
        191 => to_unsigned(40102, 16),  -- idx 191, r2=0.7461, M=1.2238
        192 => to_unsigned(40141, 16),  -- idx 192, r2=0.7500, M=1.2250
        193 => to_unsigned(40179, 16),  -- idx 193, r2=0.7539, M=1.2262
        194 => to_unsigned(40218, 16),  -- idx 194, r2=0.7578, M=1.2274
        195 => to_unsigned(40256, 16),  -- idx 195, r2=0.7617, M=1.2285
        196 => to_unsigned(40294, 16),  -- idx 196, r2=0.7656, M=1.2297
        197 => to_unsigned(40333, 16),  -- idx 197, r2=0.7695, M=1.2309
        198 => to_unsigned(40371, 16),  -- idx 198, r2=0.7734, M=1.2320
        199 => to_unsigned(40410, 16),  -- idx 199, r2=0.7773, M=1.2332
        200 => to_unsigned(40448, 16),  -- idx 200, r2=0.7812, M=1.2344
        201 => to_unsigned(40486, 16),  -- idx 201, r2=0.7852, M=1.2355
        202 => to_unsigned(40525, 16),  -- idx 202, r2=0.7891, M=1.2367
        203 => to_unsigned(40563, 16),  -- idx 203, r2=0.7930, M=1.2379
        204 => to_unsigned(40602, 16),  -- idx 204, r2=0.7969, M=1.2391
        205 => to_unsigned(40640, 16),  -- idx 205, r2=0.8008, M=1.2402
        206 => to_unsigned(40678, 16),  -- idx 206, r2=0.8047, M=1.2414
        207 => to_unsigned(40717, 16),  -- idx 207, r2=0.8086, M=1.2426
        208 => to_unsigned(40755, 16),  -- idx 208, r2=0.8125, M=1.2437
        209 => to_unsigned(40794, 16),  -- idx 209, r2=0.8164, M=1.2449
        210 => to_unsigned(40832, 16),  -- idx 210, r2=0.8203, M=1.2461
        211 => to_unsigned(40870, 16),  -- idx 211, r2=0.8242, M=1.2473
        212 => to_unsigned(40909, 16),  -- idx 212, r2=0.8281, M=1.2484
        213 => to_unsigned(40947, 16),  -- idx 213, r2=0.8320, M=1.2496
        214 => to_unsigned(40986, 16),  -- idx 214, r2=0.8359, M=1.2508
        215 => to_unsigned(41024, 16),  -- idx 215, r2=0.8398, M=1.2520
        216 => to_unsigned(41062, 16),  -- idx 216, r2=0.8438, M=1.2531
        217 => to_unsigned(41101, 16),  -- idx 217, r2=0.8477, M=1.2543
        218 => to_unsigned(41139, 16),  -- idx 218, r2=0.8516, M=1.2555
        219 => to_unsigned(41178, 16),  -- idx 219, r2=0.8555, M=1.2567
        220 => to_unsigned(41216, 16),  -- idx 220, r2=0.8594, M=1.2578
        221 => to_unsigned(41254, 16),  -- idx 221, r2=0.8633, M=1.2590
        222 => to_unsigned(41293, 16),  -- idx 222, r2=0.8672, M=1.2602
        223 => to_unsigned(41331, 16),  -- idx 223, r2=0.8711, M=1.2613
        224 => to_unsigned(41370, 16),  -- idx 224, r2=0.8750, M=1.2625
        225 => to_unsigned(41408, 16),  -- idx 225, r2=0.8789, M=1.2637
        226 => to_unsigned(41446, 16),  -- idx 226, r2=0.8828, M=1.2648
        227 => to_unsigned(41485, 16),  -- idx 227, r2=0.8867, M=1.2660
        228 => to_unsigned(41523, 16),  -- idx 228, r2=0.8906, M=1.2672
        229 => to_unsigned(41562, 16),  -- idx 229, r2=0.8945, M=1.2684
        230 => to_unsigned(41600, 16),  -- idx 230, r2=0.8984, M=1.2695
        231 => to_unsigned(41638, 16),  -- idx 231, r2=0.9023, M=1.2707
        232 => to_unsigned(41677, 16),  -- idx 232, r2=0.9062, M=1.2719
        233 => to_unsigned(41715, 16),  -- idx 233, r2=0.9102, M=1.2730
        234 => to_unsigned(41754, 16),  -- idx 234, r2=0.9141, M=1.2742
        235 => to_unsigned(41792, 16),  -- idx 235, r2=0.9180, M=1.2754
        236 => to_unsigned(41830, 16),  -- idx 236, r2=0.9219, M=1.2766
        237 => to_unsigned(41869, 16),  -- idx 237, r2=0.9258, M=1.2777
        238 => to_unsigned(41907, 16),  -- idx 238, r2=0.9297, M=1.2789
        239 => to_unsigned(41946, 16),  -- idx 239, r2=0.9336, M=1.2801
        240 => to_unsigned(41984, 16),  -- idx 240, r2=0.9375, M=1.2812
        241 => to_unsigned(42022, 16),  -- idx 241, r2=0.9414, M=1.2824
        242 => to_unsigned(42061, 16),  -- idx 242, r2=0.9453, M=1.2836
        243 => to_unsigned(42099, 16),  -- idx 243, r2=0.9492, M=1.2848
        244 => to_unsigned(42138, 16),  -- idx 244, r2=0.9531, M=1.2859
        245 => to_unsigned(42176, 16),  -- idx 245, r2=0.9570, M=1.2871
        246 => to_unsigned(42214, 16),  -- idx 246, r2=0.9609, M=1.2883
        247 => to_unsigned(42253, 16),  -- idx 247, r2=0.9648, M=1.2895
        248 => to_unsigned(42291, 16),  -- idx 248, r2=0.9688, M=1.2906
        249 => to_unsigned(42330, 16),  -- idx 249, r2=0.9727, M=1.2918
        250 => to_unsigned(42368, 16),  -- idx 250, r2=0.9766, M=1.2930
        251 => to_unsigned(42406, 16),  -- idx 251, r2=0.9805, M=1.2941
        252 => to_unsigned(42445, 16),  -- idx 252, r2=0.9844, M=1.2953
        253 => to_unsigned(42483, 16),  -- idx 253, r2=0.9883, M=1.2965
        254 => to_unsigned(42522, 16),  -- idx 254, r2=0.9922, M=1.2977
        255 => to_unsigned(42560, 16),  -- idx 255, r2=0.9961, M=1.2988
        256 => to_unsigned(42598, 16)   -- idx 256, r2=1.0000, M=1.3000
    );

    -- ---- Scanline shape LUT: 32 entries, Q0.8 ----
    -- Triangular, gap = 64/255 = 0.251
    type sl_lut_t is array (0 to 31) of unsigned(7 downto 0);
    constant SCANLINE_LUT : sl_lut_t := (
         0 => to_unsigned(255, 8),  -- phase 0.000, bright=1.000
         1 => to_unsigned(244, 8),  -- phase 0.031, bright=0.957
         2 => to_unsigned(232, 8),  -- phase 0.062, bright=0.910
         3 => to_unsigned(220, 8),  -- phase 0.094, bright=0.863
         4 => to_unsigned(208, 8),  -- phase 0.125, bright=0.816
         5 => to_unsigned(196, 8),  -- phase 0.156, bright=0.769
         6 => to_unsigned(184, 8),  -- phase 0.188, bright=0.722
         7 => to_unsigned(172, 8),  -- phase 0.219, bright=0.675
         8 => to_unsigned(160, 8),  -- phase 0.250, bright=0.627
         9 => to_unsigned(148, 8),  -- phase 0.281, bright=0.580
        10 => to_unsigned(136, 8),  -- phase 0.312, bright=0.533
        11 => to_unsigned(124, 8),  -- phase 0.344, bright=0.486
        12 => to_unsigned(112, 8),  -- phase 0.375, bright=0.439
        13 => to_unsigned(100, 8),  -- phase 0.406, bright=0.392
        14 => to_unsigned(88, 8),  -- phase 0.438, bright=0.345
        15 => to_unsigned(76, 8),  -- phase 0.469, bright=0.298
        16 => to_unsigned(64, 8),  -- phase 0.500, bright=0.251
        17 => to_unsigned(76, 8),  -- phase 0.531, bright=0.298
        18 => to_unsigned(88, 8),  -- phase 0.562, bright=0.345
        19 => to_unsigned(100, 8),  -- phase 0.594, bright=0.392
        20 => to_unsigned(112, 8),  -- phase 0.625, bright=0.439
        21 => to_unsigned(124, 8),  -- phase 0.656, bright=0.486
        22 => to_unsigned(136, 8),  -- phase 0.688, bright=0.533
        23 => to_unsigned(148, 8),  -- phase 0.719, bright=0.580
        24 => to_unsigned(160, 8),  -- phase 0.750, bright=0.627
        25 => to_unsigned(172, 8),  -- phase 0.781, bright=0.675
        26 => to_unsigned(184, 8),  -- phase 0.812, bright=0.722
        27 => to_unsigned(196, 8),  -- phase 0.844, bright=0.769
        28 => to_unsigned(208, 8),  -- phase 0.875, bright=0.816
        29 => to_unsigned(220, 8),  -- phase 0.906, bright=0.863
        30 => to_unsigned(232, 8),  -- phase 0.938, bright=0.910
        31 => to_unsigned(244, 8)   -- phase 0.969, bright=0.957
    );
end package;
